### ISSUE TITLE
🐛 BUG: Component attributes with long values are not properly splitted in multiple lines

### ISSUE THREAD

**Issue by Princesseuh** [snowpackjs/prettier-plugin-astro#37]
### Describe the Bug

[My component](https://github.com/Princesseuh/astro-social-images) takes attributes that can have values that are really long, especially arrays. The problem isn't exclusive to arrays but, for other types there's not much solutions outside of putting it on its own line. 

Currently, the plugin generate the following formatting which is not really pleasant to read:

```astro
<SocialImage
  texts={[{ content: "Princesseuh", attributes: { x: "55", y: "105", "font-size": "70px", fill: "#fefffe" } }, { content: "Introducing Astro: Ship Less JavaScript", attributes: { x: "50", y: "325", "font-size": "40px", fill: "#fefffe" } }]} />
```

I think it would be better to generate something that looks maybe like this:

```astro
<SocialImage
  texts={[
    { content: "Princesseuh", attributes: { x: "55", y: "105", "font-size": "70px", fill: "#fefffe" } },
    { content: "Introducing Astro: Ship Less JavaScript", attributes: { x: "50", y: "325", "font-size": "40px", fill: "#fefffe" } }
  ]} />
```

Where the arrays elements get splitted at least on their own lines if they're too long (longer than printWidth perhaps? Or close to)

For context, Prettier produce the following result in Javascript: 

```js
const arrayTest = [
  {
    content: "Princesseuh",
    attributes: { x: "55", y: "105", "font-size": "70px", fill: "#fefffe" },
  },
  {
    content: "Introducing Astro: Ship Less JavaScript",
    attributes: { x: "50", y: "325", "font-size": "40px", fill: "#fefffe" },
  },
]
```

Which, in my opinion, is even better than what I'm suggesting, but either would definitely be an improvement over the current result

## Current workaround

A way to workaround this at the moment is to manually format it and add a prettier-ignore comment before the array, like this:

```astro
<SocialImage
  texts={// prettier-ignore
  [
    { content: "Princesseuh", attributes: { x: "55", y: "105", "font-size": "70px", fill: "#fefffe" } },
    { content: "Introducing Astro: Ship Less JavaScript", attributes: { x: "50", y: "325", "font-size": "40px", fill: "#fefffe" } }
  ]} />
```

### Steps to Reproduce

1. Create a component with long parameters
2. Run prettier with the plugin enabled
3. Lines will be too long

**Comment by antonyfaris** [comment]
I will open a pr to fix this and add more tests for other prettier options with some fixes. I already made a lot of progress and fixed this bug.
