### ISSUE TITLE
🐛 BUG: style tag don't get line wrap

### ISSUE THREAD

**Issue by Ayc0** [snowpackjs/prettier-plugin-astro#40]
### Describe the Bug

When saving in a file, this plugin removes all line breaks in the `style` tag when not top level:

![image](https://user-images.githubusercontent.com/22725671/137824771-93cd392d-b59e-4c6c-b7ee-89db6d0a9b79.png)

Here is a picture of the same Astro code when with the `style` tag top level:

![image](https://user-images.githubusercontent.com/22725671/137824894-a218fd64-5bad-4292-93fd-279433cd4dab.png)

### Steps to Reproduce

1. install "prettier-plugin-astro": "^0.0.9"
2. in an Astro file, create an `style` tag (with or without lang prop) and put some styles in it
3. save

**Comment by antonyfaris** [comment]
There is a fix for this coming soon, including the sass tag.

**Comment by Ayc0** [comment]
@antonyfaris, is it this PR: https://github.com/snowpackjs/prettier-plugin-astro/pull/47?

**Comment by antonyfaris** [comment]
> @antonyfaris, is it this PR: #47?

The fix for this issue is not in that PR. I will open another PR after that one is closed.
