### ISSUE TITLE
💡 RFC: Test on Windows and macOS in addition to Linux

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/prettier-plugin-astro#50]
### Background & Motivation

I want to make sure our tests pass on all supported OS's as discussed in #48 

### Possible solutions
Copy the test action from the main Astro repo
### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by antonyfaris** [comment]
While on the topic of changing the workflow maybe adding node 16 would be a good idea since it's now the active LTS.
Something like [this](https://github.com/antonyfaris/sample-ava-ts/blob/main/.github/workflows/ci.yml).
