### ISSUE TITLE
🐛 BUG: Spread properties are not handled correctly

### ISSUE THREAD

**Issue by christian-fuss** [snowpackjs/prettier-plugin-astro#65]
### Describe the Bug

When using spread properties on astro components, the formatter ignores the file because of the `Error: Unhandled node type "Spread"`.

### Steps to Reproduce

1. create a `const meta = { title: "My Title", lang: "en" }`
2. spread the object on a component as props `<BaseLayout {...meta}>Foo</BaseLayout>`
3. Error! Formatter fails with `Error: Unhandled node type "Spread"`.

**Comment by antonyfaris** [comment]
I know why this is happening I will open a pr for this.
