### ISSUE TITLE
🐛 BUG: HTML comment that is a last child prevents plugin from working

### ISSUE THREAD

**Issue by innermatrix** [snowpackjs/prettier-plugin-astro#69]
### Describe the Bug

Input: 

```
<div>
<a       ></a>
<!-- test -->
</div>
```

Output: unchanged

Works fine if `a` is after comment.

In 0.9, 0.10.

### Steps to Reproduce

See above.

**Comment by antonyfaris** [comment]
I can't reproduce this.

**Comment by innermatrix** [comment]
You're right; it's fixed in 0.10, but my VSCode had 0.9 loaded in memory. After relaunching VSCode, it's working fine.
