### ISSUE TITLE
💡 RFC: Setup prerelease publishing + PR publishing

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/prettier-plugin-astro#8]
### Background & Motivation

I want to setup https://github.com/snowpackjs/astro/blob/main/.github/workflows/release.yml on the repo + sort out how to actually publish the package as well, but only in a *very* *very* beta form.

### Possible solutions
Just copy https://github.com/snowpackjs/astro/blob/main/.github/workflows/release.yml wholly into the project
### Open Questions
I guess @snowpackjs/maintainers-core has the perms to setup the npm package?

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by FredKSchott** [comment]
sounds good to me! Happy to review PRs. Most code can probably be copied.

**Comment by jasikpark** [comment]
> sounds good to me! Happy to review PRs. Most code can probably be copied.

If you could help me sort out how to set up the changesetbot integration & whatnot, that'd be great 😅

**Comment by jasikpark** [comment]
Done in #9!
